backend:
  name: github
  repo: austinmielke/carpenter-bar

media_folder: static/assets
collections:
  - name: menu
    label: Signature Cocktails Menu
    folder: src/menu
    create: true
    fields:
      - name: title
        label: Cocktails
        widget: list
        fields:
          - { name: title, label: Cocktail Name }
          - {
              name: price,
              label: Cocktail Price,
              widget: number,
              valueType: "int",
              hint: "Enter a price without a decimal or dollar sign, eg. '9' for a price of '$9'",
            }
          - { name: description, label: Cocktail Description, widget: text }
