backend:
  name: git-gateway
  branch: master

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "menu"
    label: "Menu"
    folder: "/static/assets"
    files:
      - file: "src/menu/menu.md"
        name: "signature-cocktails"
        label: "Signature Cocktails"
        fields:
          - name: "cocktails"
            lable: "Cocktails"
            widget: "list"
            fields:
              - { name: "cocktail", lable: "Cocktail Name" }
              - { name: "price", label: "Cocktail Price", widget: "number" }
              - { name: "desc", label: "Cockatil Description", widget: "text" }
