backend:
  name: git-gateway
  branch: master

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "menu"
    label: "Signature Cocktails"
    file: "menu.md"
    fields:
      - name: "cocktails"
        lable: "Cocktails"
        widget: "list"
        fields:
          - { name: "cocktail", lable: "Cocktail Name" }
          - { name: "price", label: "Cocktail Price", widget: "number" }
          - { name: "desc", label: "Cockatil Description", widget: "text" }
