backend:
  name: github
  repo: austinmielke/carpenter-bar

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "menu"
    label: "Menu"
    create: false
    folder: "src/menu/"
    field:
      - label: "Signature Cocktails"
        name: "signatureCocktails"
        widget: "list"
        fields:
          - {
            label: "Cocktail Name",
            name: "name",
            widget: "string",
          }
          - { name: "price", label: "Cocktail Price", widget: "number", valueType: "int", hint: "Type price without dollar sign or decimal point" }
          - { name: "desc", label: "Cockatil Description", widget: "text" }
