backend:
  name: git-gateway
  branch: master

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "menu"
    label: "Menu"
    create: true
    files:
      - file: "src/menu/signature-cocktail.md"
        name: "signatureCocktails"
        label: "Signature Cocktails"
        fields:
          - label: "Cocktails"
            name: "cocktails"
            widget: "list"
            fields:
              - {
                label: "Cocktail Name",
                name: "name",
                widget: "string",
              }
              - { name: "price", label: "Cocktail Price", widget: "number", valueType: "int", hint: "Type price without dollar sign or decimal point" }
              - { name: "desc", label: "Cockatil Description", widget: "text" }
