backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Signature Cocktails"
    file: "src/menu/menu.md"
    fields:
      - name: "cocktails"
        lable: "Cocktails"
        widget: "list"
        fields:
          - {name: "cocktail", lable: "Cocktail Name"}
          - {name: "price", label: "Cocktail Price", widget: "number"}
          - {name: "desc", label: "Cockatil Description" widget: "text"}
      